import { useEffect, useState, useRef } from 'react';
import { createPortal } from 'react-dom';
import { Plus, Edit2, Loader2, Save, Upload } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import Editor from '@/components/cms/Editor';
import { BlogPost, BLOG_POSTS } from '@/data/posts';
import { toast } from 'sonner';
import { cn } from "@/lib/utils";
import { useAuth } from '@/contexts/AuthContext';
import { useImageUpload } from '@/hooks/useImageUpload';

interface AdminFeedProps {
    isDarkMode: boolean;
}

const AdminFeed = ({ isDarkMode }: AdminFeedProps) => {
    const { user } = useAuth();
    const [posts, setPosts] = useState<BlogPost[]>([]);
    const [fetching, setFetching] = useState(true);
    const [editingPost, setEditingPost] = useState<BlogPost | null>(null);
    const [editorContent, setEditorContent] = useState('');
    const [isSaving, setIsSaving] = useState(false);

    const fileInputRef = useRef<HTMLInputElement>(null);
    const { uploadImage, uploading: isUploadingImage } = useImageUpload();

    // Fetch posts
    useEffect(() => {
        const fetchPosts = async () => {
            setFetching(true);
            const { data, error } = await supabase
                .from('posts')
                .select('*')
                .order('date', { ascending: false });

            if (!error && data && data.length > 0) {
                setPosts(data as BlogPost[]);
            } else {
                setPosts(Object.values(BLOG_POSTS));
            }
            setFetching(false);
        };

        if (user) {
            fetchPosts();
        }
    }, [user]);

    const handleEdit = (post: BlogPost) => {
        setEditingPost(post);
        setEditorContent(post.content || '');
    };

    const handleCreate = () => {
        const newPost: BlogPost = {
            id: '', // Will be generated by DB
            slug: 'new-post-' + Date.now(),
            title: '',
            content: '<p>Start writing...</p>',
            date: new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }),
            category: 'Thoughts',
            readTime: '5 min read',
            image: '',
            description: 'New draft...',
            status: 'draft'
        } as BlogPost;
        setEditingPost(newPost);
        setEditorContent(newPost.content || '');
    }

    const handleSave = async () => {
        if (!editingPost) return;
        setIsSaving(true);

        // Remove id if it's empty to let DB generate it (if creating)
        const postToSave = { ...editingPost, content: editorContent, updated_at: new Date().toISOString() };
        if (!postToSave.id) delete (postToSave as any).id;

        const { error } = await supabase
            .from('posts')
            .upsert(postToSave)
            .select();

        if (error) {
            toast.error("Failed to save: " + error.message);
        } else {
            toast.success("Content secured.");
            setEditingPost(null);
            // Re-fetch posts
            const { data } = await supabase.from('posts').select('*').order('date', { ascending: false });
            if (data) setPosts(data as BlogPost[]);
        }
        setIsSaving(false);
    };

    const handleImageSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0] && editingPost) {
            const url = await uploadImage(e.target.files[0]);
            if (url) {
                setEditingPost({ ...editingPost, image: url });
            }
        }
    };

    if (editingPost) {
        const headerActions = document.getElementById('admin-header-actions');

        return (
            <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 pb-24">
                {headerActions && createPortal(
                    <button
                        onClick={handleSave}
                        disabled={isSaving}
                        className="flex items-center gap-2 px-6 py-2 bg-accent text-white rounded-full font-bold text-xs uppercase tracking-widest hover:brightness-110 transition-all shadow-lg"
                    >
                        {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                        Save
                    </button>,
                    headerActions
                )}

                <div className="max-w-3xl mx-auto space-y-8">
                    {/* Big Title & Slug */}
                    <div className="space-y-4">
                        <input
                            type="text"
                            value={editingPost.title}
                            onChange={(e) => setEditingPost({ ...editingPost, title: e.target.value })}
                            className={cn(
                                "w-full text-5xl lg:text-7xl font-serif font-black bg-transparent outline-none placeholder-opacity-30 leading-tight",
                                isDarkMode ? "text-white placeholder-white" : "text-gray-900 placeholder-gray-300"
                            )}
                            placeholder="Untitled"
                        />
                        <div className={cn("flex items-center gap-2 font-mono text-xs lg:text-sm opacity-60", isDarkMode ? "text-gray-400" : "text-gray-600")}>
                            <span>https://danjimmerson.com/feed/</span>
                            <input
                                type="text"
                                value={editingPost.slug}
                                onChange={(e) => setEditingPost({ ...editingPost, slug: e.target.value })}
                                className="bg-transparent outline-none border-b border-dashed border-current min-w-[200px]"
                                placeholder="post-slug"
                            />
                        </div>
                    </div>

                    {/* Metadata Grid */}
                    <div className={cn(
                        "grid grid-cols-1 md:grid-cols-3 gap-6 p-6 rounded-2xl border",
                        isDarkMode ? "bg-white/5 border-white/10" : "bg-gray-50 border-gray-100"
                    )}>
                        {/* Featured Image */}
                        <div className="space-y-2">
                            <label className="text-[10px] uppercase tracking-widest font-bold opacity-50">Featured Image</label>
                            <div
                                onClick={() => fileInputRef.current?.click()}
                                className={cn(
                                    "aspect-video rounded-lg overflow-hidden border border-dashed flex items-center justify-center cursor-pointer group relative transition-all",
                                    isDarkMode ? "border-white/20 hover:border-accent hover:bg-white/5" : "border-gray-300 hover:border-accent hover:bg-white"
                                )}
                            >
                                <input
                                    type="file"
                                    ref={fileInputRef}
                                    className="hidden"
                                    accept="image/*"
                                    onChange={handleImageSelect}
                                />
                                {isUploadingImage ? (
                                    <Loader2 className="w-8 h-8 animate-spin opacity-50" />
                                ) : editingPost.image ? (
                                    <>
                                        <img src={editingPost.image} alt="Cover" className="w-full h-full object-cover" />
                                        <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 flex items-center justify-center text-xs font-bold uppercase tracking-widest text-white transition-opacity">
                                            <Upload className="w-4 h-4 mr-2" /> Change Image
                                        </div>
                                    </>
                                ) : (
                                    <span className="text-xs font-bold uppercase tracking-widest opacity-50">Add Cover</span>
                                )}
                            </div>
                        </div>

                        {/* Date & Category & Status */}
                        <div className="col-span-1 md:col-span-2 space-y-6">
                            <div className="grid grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <label className="text-[10px] uppercase tracking-widest font-bold opacity-50">Publish Date</label>
                                    <input
                                        type="date"
                                        value={new Date(editingPost.date).toISOString().split('T')[0]}
                                        onChange={(e) => {
                                            const date = new Date(e.target.value);
                                            // Adjust for timezone offset to prevent off-by-one errors
                                            const userTimezoneOffset = date.getTimezoneOffset() * 60000;
                                            const adjustedDate = new Date(date.getTime() + userTimezoneOffset);
                                            setEditingPost({ ...editingPost, date: adjustedDate.toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }) });
                                        }}
                                        className={cn(
                                            "w-full bg-transparent border-b outline-none py-2 font-mono text-sm",
                                            isDarkMode ? "border-white/20 focus:border-white" : "border-gray-300 focus:border-black"
                                        )}
                                    />
                                </div>
                                <div className="space-y-2">
                                    <label className="text-[10px] uppercase tracking-widest font-bold opacity-50">Status</label>
                                    <select
                                        value={editingPost.status || 'draft'}
                                        onChange={(e) => setEditingPost({ ...editingPost, status: e.target.value as any })}
                                        className={cn(
                                            "w-full bg-transparent border-b outline-none py-2 font-mono text-sm uppercase cursor-pointer",
                                            isDarkMode ? "border-white/20 focus:border-white text-white option:text-black" : "border-gray-300 focus:border-black text-black"
                                        )}
                                    >
                                        <option value="draft" className="text-black">Draft</option>
                                        <option value="published" className="text-black">Published</option>
                                        <option value="trash" className="text-black">Trash</option>
                                    </select>
                                </div>
                            </div>

                            <div className="space-y-2">
                                <label className="text-[10px] uppercase tracking-widest font-bold opacity-50">Category / Tag</label>
                                <div className="flex flex-wrap gap-2">
                                    {Array.from(new Set(posts.map(p => p.category))).map(cat => (
                                        <button
                                            key={cat}
                                            onClick={() => setEditingPost({ ...editingPost, category: cat })}
                                            className={cn(
                                                "px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest border transition-all",
                                                editingPost.category === cat
                                                    ? "bg-accent border-accent text-white"
                                                    : (isDarkMode ? "border-white/20 hover:border-white text-gray-400" : "border-gray-200 hover:border-black text-gray-500")
                                            )}
                                        >
                                            {cat}
                                        </button>
                                    ))}
                                    <button
                                        onClick={() => {
                                            const newCat = window.prompt("New Tag Name");
                                            if (newCat) setEditingPost({ ...editingPost, category: newCat });
                                        }}
                                        className={cn(
                                            "px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest border border-dashed transition-all opacity-50 hover:opacity-100",
                                            isDarkMode ? "border-white/40 hover:border-white" : "border-gray-400 hover:border-black"
                                        )}
                                    >
                                        + Create
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Editor Area */}
                    <div>
                        <Editor content={editorContent} onChange={setEditorContent} isDarkMode={isDarkMode} />
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="space-y-8 animate-in fade-in duration-500">
            <div className="flex items-center justify-between">
                <div>
                    <h2 className={cn("text-3xl font-serif font-bold", isDarkMode ? "text-white" : "text-gray-900")}>Feed Content</h2>
                    <p className={cn("text-sm mt-1", isDarkMode ? "text-gray-400" : "text-gray-500")}>Manage your digital transmissions.</p>
                </div>
                <button
                    onClick={handleCreate}
                    className={cn(
                        "flex items-center gap-2 px-6 py-3 rounded-full font-bold text-xs uppercase tracking-widest transition-all shadow-lg hover:shadow-xl",
                        isDarkMode ? "bg-white text-black hover:bg-gray-200" : "bg-black text-white hover:bg-gray-800"
                    )}
                >
                    <Plus className="w-4 h-4" /> New Entry
                </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {fetching ? (
                    <div className="col-span-full py-20 text-center font-mono text-xs animate-pulse opacity-50">Searching...</div>
                ) : (
                    posts.map((post) => (
                        <div key={post.id} className={cn(
                            "group p-6 rounded-3xl border transition-all duration-300 flex flex-col h-full relative overflow-hidden",
                            isDarkMode ? "bg-white/5 border-white/10 hover:border-white/30 hover:bg-white/10" : "bg-white border-gray-200 hover:border-gray-300 hover:shadow-xl"
                        )}>
                            <div className="aspect-video rounded-xl overflow-hidden mb-4 bg-gray-900 relative">
                                {post.image && <img src={post.image} alt={post.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 opacity-80 group-hover:opacity-100" />}
                                <div className="absolute top-2 right-2 px-2 py-1 bg-black/80 backdrop-blur rounded text-[9px] font-bold uppercase tracking-widest text-white border border-white/10">
                                    {post.category}
                                </div>
                                {/* Status Badge */}
                                <div className={cn(
                                    "absolute top-2 left-2 px-2 py-1 backdrop-blur rounded text-[9px] font-bold uppercase tracking-widest text-white border border-white/10 shadow-lg",
                                    post.status === 'published' ? "bg-green-600/90" :
                                        post.status === 'trash' ? "bg-red-600/90" :
                                            "bg-yellow-600/90"
                                )}>
                                    {post.status || 'draft'}
                                </div>
                            </div>
                            <h3 className={cn("font-serif font-bold text-xl mb-2 leading-tight transition-colors line-clamp-2", isDarkMode ? "text-gray-200 group-hover:text-white" : "text-gray-900")}>
                                {post.title || "Untitled"}
                            </h3>
                            <div className={cn("mt-auto pt-4 flex items-center justify-between text-[10px] font-bold uppercase tracking-widest border-t", isDarkMode ? "text-gray-500 border-white/5" : "text-gray-400 border-gray-100")}>
                                <span>{post.date}</span>
                                <button
                                    onClick={() => handleEdit(post)}
                                    className="flex items-center gap-1 hover:text-accent transition-colors"
                                >
                                    <Edit2 className="w-3 h-3" /> Edit
                                </button>
                            </div>
                        </div>
                    ))
                )}
            </div>
        </div>
    );
};

export default AdminFeed;
