import { useEffect, useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { Navigate } from 'react-router-dom';
import Navigation from '@/components/Navigation';
import { LogOut, Plus, Edit2, Loader2, Save, Trash2, LayoutGrid } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import Editor from '@/components/cms/Editor';
import { BlogPost, BLOG_POSTS } from '@/data/posts';
import { toast } from 'sonner';
import TrippyVisuals from '@/components/TrippyVisuals';

const Admin = () => {
    const { user, loading } = useAuth();
    const [posts, setPosts] = useState<BlogPost[]>([]);
    const [fetching, setFetching] = useState(true);
    const [editingPost, setEditingPost] = useState<BlogPost | null>(null);
    const [editorContent, setEditorContent] = useState('');
    const [isSaving, setIsSaving] = useState(false);

    // Fetch posts
    useEffect(() => {
        const fetchPosts = async () => {
            setFetching(true);
            const { data, error } = await supabase
                .from('posts')
                .select('*')
                .order('date', { ascending: false });

            if (!error && data && data.length > 0) {
                setPosts(data as BlogPost[]);
            } else {
                setPosts(Object.values(BLOG_POSTS));
            }
            setFetching(false);
        };

        if (user) {
            fetchPosts();
        }
    }, [user]);

    if (loading) {
        return <div className="min-h-screen bg-black text-white flex items-center justify-center font-mono">LOADING SYSTEM...</div>;
    }

    if (!user) {
        return <Navigate to="/login" />;
    }

    if (user.email !== 'jimmerson@gmail.com') {
        return (
            <div className="min-h-screen bg-black text-white flex flex-col items-center justify-center font-mono">
                <div className="text-red-500 font-bold mb-4 uppercase tracking-widest text-xl animate-pulse">Access Denied</div>
                <p className="text-gray-500 text-sm mb-8">Unauthorized biometrics detected.</p>
                <button
                    onClick={() => supabase.auth.signOut()}
                    className="px-6 py-3 border border-white/20 rounded-full hover:bg-white/10 transition-all text-sm uppercase tracking-widest"
                >
                    Return to Safety
                </button>
            </div>
        );
    }

    const handleLogout = async () => {
        await supabase.auth.signOut();
    };

    const handleEdit = (post: BlogPost) => {
        setEditingPost(post);
        setEditorContent(post.content || '');
    };

    const handleCreate = () => {
        const newPost: BlogPost = {
            id: '', // Will be generated by DB
            slug: 'new-post-' + Date.now(),
            title: 'Untitled Post',
            content: '<p>Start writing...</p>',
            date: new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }),
            category: 'Thoughts',
            readTime: '5 min read',
            image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1964',
            description: 'New draft...'
        } as BlogPost; // Simplified for demo
        setEditingPost(newPost);
        setEditorContent(newPost.content || '');
    }

    const handleSave = async () => {
        if (!editingPost) return;
        setIsSaving(true);

        // Remove id if it's empty to let DB generate it (if creating)
        const postToSave = { ...editingPost, content: editorContent, updated_at: new Date().toISOString() };
        if (!postToSave.id) delete (postToSave as any).id;

        const { error } = await supabase
            .from('posts')
            .upsert(postToSave)
            .select();

        if (error) {
            toast.error("Failed to save: " + error.message);
        } else {
            toast.success("Content secured.");
            setEditingPost(null);
            // Refresh list logic would go here
        }
        setIsSaving(false);
    };

    return (
        <div className="min-h-screen bg-black flex flex-col relative text-white selection:bg-accent selection:text-black">
            <div className="fixed inset-0 z-0 opacity-30 pointer-events-none">
                <TrippyVisuals isPlaying={true} mode={1} />
            </div>

            <div className="relative z-10 w-full pt-8">
                <Navigation alwaysShowBackground={false} />
            </div>

            <main className="pt-24 px-6 lg:px-12 pb-24 relative z-10">
                <div className="container mx-auto max-w-6xl">
                    <div className="flex items-center justify-between mb-12">
                        <div>
                            <span className="text-accent text-[10px] font-bold uppercase tracking-[0.2em] animate-pulse">Root Access Granted</span>
                            <h1 className="text-4xl lg:text-5xl font-serif font-bold mt-2 text-transparent bg-clip-text bg-gradient-to-r from-white to-gray-400">
                                {editingPost ? 'Edit Protocol' : 'Data Matrix'}
                            </h1>
                        </div>
                        <div className="flex gap-4">
                            {editingPost ? (
                                <>
                                    <button
                                        onClick={() => setEditingPost(null)}
                                        className="px-6 py-3 rounded-full font-bold text-xs uppercase tracking-widest border border-white/20 hover:bg-white/10 transition-all text-white/70 hover:text-white"
                                    >
                                        Abort
                                    </button>
                                    <button
                                        onClick={handleSave}
                                        disabled={isSaving}
                                        className="flex items-center gap-2 px-6 py-3 bg-white text-black rounded-full font-bold text-xs uppercase tracking-widest hover:bg-accent hover:scale-105 transition-all shadow-lg hover:shadow-accent/50"
                                    >
                                        {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                                        Commit Changes
                                    </button>
                                </>
                            ) : (
                                <button
                                    onClick={handleLogout}
                                    className="flex items-center gap-2 px-6 py-3 rounded-full font-bold text-xs uppercase tracking-widest border border-white/20 hover:bg-red-500/10 hover:border-red-500/50 hover:text-red-400 transition-all group"
                                >
                                    <LogOut className="w-4 h-4 group-hover:translate-x-1 transition-transform" /> Disconnect
                                </button>
                            )}
                        </div>
                    </div>

                    {editingPost ? (
                        <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 bg-black/50 backdrop-blur-xl p-8 rounded-3xl border border-white/10 shadow-2xl">
                            <div className="mb-6 grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div>
                                    <label className="block text-[10px] font-bold uppercase tracking-widest text-gray-500 mb-2">Title</label>
                                    <input
                                        type="text"
                                        value={editingPost.title}
                                        onChange={(e) => setEditingPost({ ...editingPost, title: e.target.value })}
                                        className="w-full text-2xl font-serif font-bold bg-transparent border-b border-white/20 focus:border-accent outline-none py-2 transition-all text-white placeholder-white/20"
                                        placeholder="Enter Title..."
                                    />
                                </div>
                                <div>
                                    <label className="block text-[10px] font-bold uppercase tracking-widest text-gray-500 mb-2">Slug</label>
                                    <input
                                        type="text"
                                        value={editingPost.slug}
                                        onChange={(e) => setEditingPost({ ...editingPost, slug: e.target.value })}
                                        className="w-full font-mono text-sm bg-transparent border-b border-white/20 focus:border-accent outline-none py-2 transition-all text-gray-400"
                                        placeholder="url-slug-here"
                                    />
                                </div>
                            </div>

                            <div className="bg-white/5 rounded-2xl p-1 border border-white/10 overflow-hidden">
                                <Editor content={editorContent} onChange={setEditorContent} />
                            </div>
                        </div>
                    ) : (
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            <button
                                onClick={handleCreate}
                                className="group relative bg-white/5 p-6 rounded-3xl border border-white/10 hover:border-accent hover:bg-white/10 transition-all duration-300 flex flex-col items-center justify-center min-h-[300px] text-gray-400 hover:text-white gap-4 backdrop-blur-sm"
                            >
                                <div className="w-16 h-16 rounded-full bg-white/5 border border-white/10 group-hover:border-accent group-hover:scale-110 flex items-center justify-center transition-all shadow-lg">
                                    <Plus className="w-8 h-8 text-gray-400 group-hover:text-accent" />
                                </div>
                                <span className="font-bold uppercase tracking-widest text-xs">Initialize New Entry</span>
                            </button>

                            {fetching ? (
                                <div className="col-span-full py-20 text-center text-gray-400 font-mono text-xs animate-pulse">Scanning database...</div>
                            ) : (
                                posts.map((post) => (
                                    <div key={post.id} className="group bg-black/40 backdrop-blur-md p-6 rounded-3xl border border-white/10 hover:border-white/30 transition-all duration-300 flex flex-col h-full hover:bg-white/5">
                                        <div className="aspect-video rounded-xl overflow-hidden mb-4 bg-gray-900 relative">
                                            {post.image && <img src={post.image} alt={post.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 opacity-80 group-hover:opacity-100" />}
                                            <div className="absolute top-2 right-2 px-2 py-1 bg-black/80 backdrop-blur rounded text-[9px] font-bold uppercase tracking-widest text-white border border-white/10">
                                                {post.category}
                                            </div>
                                        </div>
                                        <h3 className="font-serif font-bold text-xl mb-2 leading-tight text-gray-200 group-hover:text-white transition-colors line-clamp-2">{post.title}</h3>
                                        <div className="mt-auto pt-4 flex items-center justify-between text-[10px] font-bold text-gray-500 uppercase tracking-widest border-t border-white/5">
                                            <span>{post.date}</span>
                                            <button
                                                onClick={() => handleEdit(post)}
                                                className="flex items-center gap-1 text-gray-400 hover:text-accent transition-colors"
                                            >
                                                <Edit2 className="w-3 h-3" /> Edit
                                            </button>
                                        </div>
                                    </div>
                                ))
                            )}
                        </div>
                    )}
                </div>
            </main>
        </div>
    );
};

export default Admin;
