import { useEffect, useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { Navigate, Link } from 'react-router-dom';
import { LogOut, Plus, Edit2, Loader2, Save, ArrowLeft, Sun, Moon } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import Editor from '@/components/cms/Editor';
import { BlogPost, BLOG_POSTS } from '@/data/posts';
import { toast } from 'sonner';
import TrippyVisuals from '@/components/TrippyVisuals';
import { cn } from "@/lib/utils";

const Admin = () => {
    const { user, loading } = useAuth();
    const [posts, setPosts] = useState<BlogPost[]>([]);
    const [fetching, setFetching] = useState(true);
    const [editingPost, setEditingPost] = useState<BlogPost | null>(null);
    const [editorContent, setEditorContent] = useState('');
    const [isSaving, setIsSaving] = useState(false);
    const [isDarkMode, setIsDarkMode] = useState(true);

    // Fetch posts
    useEffect(() => {
        const fetchPosts = async () => {
            setFetching(true);
            const { data, error } = await supabase
                .from('posts')
                .select('*')
                .order('date', { ascending: false });

            if (!error && data && data.length > 0) {
                setPosts(data as BlogPost[]);
            } else {
                setPosts(Object.values(BLOG_POSTS));
            }
            setFetching(false);
        };

        if (user) {
            fetchPosts();
        }
    }, [user]);

    if (loading) {
        return <div className="min-h-screen bg-black text-white flex items-center justify-center font-mono">LOADING SYSTEM...</div>;
    }

    if (!user) {
        return <Navigate to="/login" />;
    }

    if (user.email !== 'jimmerson@gmail.com') {
        return (
            <div className="min-h-screen bg-black text-white flex flex-col items-center justify-center font-mono">
                <div className="text-red-500 font-bold mb-4 uppercase tracking-widest text-xl animate-pulse">Access Denied</div>
                <p className="text-gray-500 text-sm mb-8">Unauthorized biometrics detected.</p>
                <button
                    onClick={() => supabase.auth.signOut()}
                    className="px-6 py-3 border border-white/20 rounded-full hover:bg-white/10 transition-all text-sm uppercase tracking-widest"
                >
                    Return to Safety
                </button>
            </div>
        );
    }

    const handleLogout = async () => {
        await supabase.auth.signOut();
    };

    const handleEdit = (post: BlogPost) => {
        setEditingPost(post);
        setEditorContent(post.content || '');
    };

    const handleCreate = () => {
        const newPost: BlogPost = {
            id: '', // Will be generated by DB
            slug: 'new-post-' + Date.now(),
            title: 'Untitled Post',
            content: '<p>Start writing...</p>',
            date: new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }),
            category: 'Thoughts',
            readTime: '5 min read',
            image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1964',
            description: 'New draft...'
        } as BlogPost; // Simplified for demo
        setEditingPost(newPost);
        setEditorContent(newPost.content || '');
    }

    const handleSave = async () => {
        if (!editingPost) return;
        setIsSaving(true);

        // Remove id if it's empty to let DB generate it (if creating)
        const postToSave = { ...editingPost, content: editorContent, updated_at: new Date().toISOString() };
        if (!postToSave.id) delete (postToSave as any).id;

        const { error } = await supabase
            .from('posts')
            .upsert(postToSave)
            .select();

        if (error) {
            toast.error("Failed to save: " + error.message);
        } else {
            toast.success("Content secured.");
            setEditingPost(null);
            // Refresh list logic would go here: re-fetch posts
        }
        setIsSaving(false);
    };

    return (
        <div className={cn(
            "min-h-screen flex flex-col relative transition-colors duration-500",
            isDarkMode ? "bg-black text-white selection:bg-accent selection:text-black" : "bg-white text-black selection:bg-accent selection:text-white"
        )}>
            {/* Trippy BG only in dark mode */}
            <div className={cn("fixed inset-0 z-0 pointer-events-none transition-opacity duration-500", isDarkMode ? "opacity-30" : "opacity-0")}>
                <TrippyVisuals isPlaying={true} mode={1} />
            </div>

            {/* Admin Header */}
            <header className={cn(
                "fixed top-0 left-0 right-0 z-50 h-16 flex items-center justify-between px-6 border-b backdrop-blur-md transition-colors",
                isDarkMode ? "bg-black/80 border-white/10" : "bg-white/80 border-gray-200"
            )}>
                <div className="flex items-center gap-4">
                    <Link to="/" className={cn("flex items-center gap-2 text-xs font-bold uppercase tracking-widest hover:text-accent transition-colors", isDarkMode ? "text-gray-400" : "text-gray-600")}>
                        <ArrowLeft className="w-4 h-4" /> Exit to Site
                    </Link>
                </div>

                <div className="flex items-center gap-4">
                    <button
                        onClick={() => setIsDarkMode(!isDarkMode)}
                        className={cn("p-2 rounded-full transition-colors", isDarkMode ? "hover:bg-white/10 text-yellow-400" : "hover:bg-gray-100 text-gray-600")}
                        title="Toggle Theme"
                    >
                        {isDarkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
                    </button>

                    {editingPost ? (
                        <>
                            <button
                                onClick={() => setEditingPost(null)}
                                className={cn("px-4 py-2 rounded-full font-bold text-xs uppercase tracking-widest border transition-all", isDarkMode ? "border-white/20 hover:bg-white/10 text-white/70 hover:text-white" : "border-gray-300 hover:bg-gray-100 text-gray-600")}
                            >
                                Cancel
                            </button>
                            <button
                                onClick={handleSave}
                                disabled={isSaving}
                                className="flex items-center gap-2 px-6 py-2 bg-accent text-white rounded-full font-bold text-xs uppercase tracking-widest hover:brightness-110 transition-all shadow-lg"
                            >
                                {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                                Save
                            </button>
                        </>
                    ) : (
                        <button
                            onClick={handleLogout}
                            className={cn("flex items-center gap-2 px-4 py-2 rounded-full font-bold text-xs uppercase tracking-widest border transition-all group", isDarkMode ? "border-white/20 hover:bg-red-500/10 hover:border-red-500/50 hover:text-red-400" : "border-gray-200 hover:bg-red-50 text-gray-500 hover:text-red-600")}
                        >
                            <LogOut className="w-4 h-4 group-hover:translate-x-1 transition-transform" /> Logout
                        </button>
                    )}
                </div>
            </header>

            <main className="pt-24 px-6 lg:px-12 pb-24 relative z-10 font-sans">
                <div className="container mx-auto max-w-6xl">
                    {!editingPost && (
                        <div className="flex items-center justify-between mb-12">
                            <div>
                                <span className="text-accent text-[10px] font-bold uppercase tracking-[0.2em] animate-pulse">System Active</span>
                                <h1 className={cn("text-4xl lg:text-5xl font-serif font-bold mt-2", isDarkMode ? "text-transparent bg-clip-text bg-gradient-to-r from-white to-gray-400" : "text-gray-900")}>
                                    Data Matrix
                                </h1>
                            </div>
                        </div>
                    )}

                    {editingPost ? (
                        <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
                            {/* Big Title & Slug */}
                            <div className="space-y-4">
                                <input
                                    type="text"
                                    value={editingPost.title}
                                    onChange={(e) => setEditingPost({ ...editingPost, title: e.target.value })}
                                    className={cn(
                                        "w-full text-5xl lg:text-7xl font-serif font-black bg-transparent outline-none placeholder-opacity-30 leading-tight",
                                        isDarkMode ? "text-white placeholder-white" : "text-gray-900 placeholder-gray-300"
                                    )}
                                    placeholder="Untitled"
                                />
                                <div className={cn("flex items-center gap-2 font-mono text-xs lg:text-sm opacity-60", isDarkMode ? "text-gray-400" : "text-gray-600")}>
                                    <span>https://elegant-dan.com/blog/</span>
                                    <input
                                        type="text"
                                        value={editingPost.slug}
                                        onChange={(e) => setEditingPost({ ...editingPost, slug: e.target.value })}
                                        className="bg-transparent outline-none border-b border-dashed border-current min-w-[200px]"
                                        placeholder="post-slug"
                                    />
                                </div>
                            </div>

                            {/* Metadata Grid */}
                            <div className={cn(
                                "grid grid-cols-1 md:grid-cols-3 gap-6 p-6 rounded-2xl border",
                                isDarkMode ? "bg-white/5 border-white/10" : "bg-gray-50 border-gray-100"
                            )}>
                                {/* Featured Image */}
                                <div className="space-y-2">
                                    <label className="text-[10px] uppercase tracking-widest font-bold opacity-50">Featured Image</label>
                                    <div
                                        onClick={() => {
                                            const url = window.prompt("Image URL", editingPost.image);
                                            if (url) setEditingPost({ ...editingPost, image: url });
                                        }}
                                        className={cn(
                                            "aspect-video rounded-lg overflow-hidden border border-dashed flex items-center justify-center cursor-pointer group relative transition-all",
                                            isDarkMode ? "border-white/20 hover:border-accent hover:bg-white/5" : "border-gray-300 hover:border-accent hover:bg-white"
                                        )}
                                    >
                                        {editingPost.image ? (
                                            <>
                                                <img src={editingPost.image} alt="Cover" className="w-full h-full object-cover" />
                                                <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 flex items-center justify-center text-xs font-bold uppercase tracking-widest text-white transition-opacity">
                                                    Change Image
                                                </div>
                                            </>
                                        ) : (
                                            <span className="text-xs font-bold uppercase tracking-widest opacity-50">Add Cover</span>
                                        )}
                                    </div>
                                </div>

                                {/* Date & Category */}
                                <div className="col-span-1 md:col-span-2 space-y-6">
                                    <div className="space-y-2">
                                        <label className="text-[10px] uppercase tracking-widest font-bold opacity-50">Publish Date</label>
                                        <input
                                            type="date"
                                            value={new Date(editingPost.date).toISOString().split('T')[0]} // Very basic handling, ideally utilize date-fns for robust parsing
                                            onChange={(e) => {
                                                const date = new Date(e.target.value);
                                                setEditingPost({ ...editingPost, date: date.toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }) });
                                            }}
                                            className={cn(
                                                "w-full bg-transparent border-b outline-none py-2 font-mono text-sm",
                                                isDarkMode ? "border-white/20 focus:border-white" : "border-gray-300 focus:border-black"
                                            )}
                                        />
                                    </div>

                                    <div className="space-y-2">
                                        <label className="text-[10px] uppercase tracking-widest font-bold opacity-50">Category / Tag</label>
                                        <div className="flex flex-wrap gap-2">
                                            {Array.from(new Set(posts.map(p => p.category))).map(cat => (
                                                <button
                                                    key={cat}
                                                    onClick={() => setEditingPost({ ...editingPost, category: cat })}
                                                    className={cn(
                                                        "px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest border transition-all",
                                                        editingPost.category === cat
                                                            ? "bg-accent border-accent text-white"
                                                            : (isDarkMode ? "border-white/20 hover:border-white text-gray-400" : "border-gray-200 hover:border-black text-gray-500")
                                                    )}
                                                >
                                                    {cat}
                                                </button>
                                            ))}
                                            <button
                                                onClick={() => {
                                                    const newCat = window.prompt("New Tag Name");
                                                    if (newCat) setEditingPost({ ...editingPost, category: newCat });
                                                }}
                                                className={cn(
                                                    "px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest border border-dashed transition-all opacity-50 hover:opacity-100",
                                                    isDarkMode ? "border-white/40 hover:border-white" : "border-gray-400 hover:border-black"
                                                )}
                                            >
                                                + Create
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Editor Area */}
                            <div>
                                <Editor content={editorContent} onChange={setEditorContent} isDarkMode={isDarkMode} />
                            </div>
                        </div>
                    ) : (
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            <button
                                onClick={handleCreate}
                                className={cn(
                                    "group relative p-6 rounded-3xl border transition-all duration-300 flex flex-col items-center justify-center min-h-[300px] gap-4 backdrop-blur-sm",
                                    isDarkMode ? "bg-white/5 border-white/10 hover:border-accent hover:bg-white/10 text-gray-400 hover:text-white" : "bg-gray-50 border-gray-200 hover:border-accent hover:bg-white text-gray-500 hover:text-black"
                                )}
                            >
                                <div className={cn("w-16 h-16 rounded-full border flex items-center justify-center transition-all shadow-lg", isDarkMode ? "bg-white/5 border-white/10 group-hover:border-accent" : "bg-white border-gray-200 group-hover:border-accent")}>
                                    <Plus className="w-8 h-8 group-hover:text-accent" />
                                </div>
                                <span className="font-bold uppercase tracking-widest text-xs">New Content</span>
                            </button>

                            {fetching ? (
                                <div className="col-span-full py-20 text-center font-mono text-xs animate-pulse opacity-50">Searching...</div>
                            ) : (
                                posts.map((post) => (
                                    <div key={post.id} className={cn(
                                        "group p-6 rounded-3xl border transition-all duration-300 flex flex-col h-full",
                                        isDarkMode ? "bg-black/40 backdrop-blur-md border-white/10 hover:border-white/30 hover:bg-white/5" : "bg-white border-gray-200 hover:border-gray-300 hover:shadow-xl"
                                    )}>
                                        <div className="aspect-video rounded-xl overflow-hidden mb-4 bg-gray-900 relative">
                                            {post.image && <img src={post.image} alt={post.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 opacity-80 group-hover:opacity-100" />}
                                            <div className="absolute top-2 right-2 px-2 py-1 bg-black/80 backdrop-blur rounded text-[9px] font-bold uppercase tracking-widest text-white border border-white/10">
                                                {post.category}
                                            </div>
                                        </div>
                                        <h3 className={cn("font-serif font-bold text-xl mb-2 leading-tight transition-colors line-clamp-2", isDarkMode ? "text-gray-200 group-hover:text-white" : "text-gray-900")}>
                                            {post.title}
                                        </h3>
                                        <div className={cn("mt-auto pt-4 flex items-center justify-between text-[10px] font-bold uppercase tracking-widest border-t", isDarkMode ? "text-gray-500 border-white/5" : "text-gray-400 border-gray-100")}>
                                            <span>{post.date}</span>
                                            <button
                                                onClick={() => handleEdit(post)}
                                                className="flex items-center gap-1 hover:text-accent transition-colors"
                                            >
                                                <Edit2 className="w-3 h-3" /> Edit
                                            </button>
                                        </div>
                                    </div>
                                ))
                            )}
                        </div>
                    )}
                </div>
            </main>
        </div>
    );
};

export default Admin;
