import { useParams, Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft, Calendar, Clock, Share2, Twitter, Linkedin, Facebook } from "lucide-react";
import Navigation from "@/components/Navigation";

const BlogPost = () => {
    const { slug } = useParams();

    const POSTS: Record<string, any> = {
        "the-future-of-brand-architecture": {
            title: "The Future of Brand Architecture",
            subtitle: "How modern companies are rethinking their structural identity in a decentralized world.",
            date: "Nov 28, 2025",
            readTime: "5 min read",
            category: "Strategy",
            author: "Dan Jimmerson",
            image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=2070",
            content: `<p class="lead">In the rapidly evolving landscape of digital business, the traditional models of brand architecture are being challenged...</p>`
        },
        "revenue-systems-that-scale": {
            title: "Revenue Systems that Scale",
            subtitle: "Building automated pipelines that turn passive attention into active revenue streams.",
            date: "Nov 25, 2025",
            readTime: "4 min read",
            category: "Business",
            author: "Dan Jimmerson",
            image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2070",
            content: `<p class="lead">Revenue is no longer just about sales; it's about systems. In the modern economy, the most successful companies are those that build automated engines...</p>`
        },
        "design-as-a-competitive-advantage": {
            title: "Design as a Competitive Advantage",
            subtitle: "Why aesthetic excellence is no longer optional for market leaders in the AI era.",
            date: "Nov 22, 2025",
            readTime: "6 min read",
            category: "Design",
            author: "Dan Jimmerson",
            image: "https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&q=80&w=2700",
            content: `<p class="lead">In an age of infinite content generated by AI, human curation and high-fidelity design become the ultimate differentiators...</p>`
        },
        "the-psychology-of-user-retention": {
            title: "The Psychology of User Retention",
            subtitle: "Understanding the cognitive biases that keep users coming back to your application.",
            date: "Nov 18, 2025",
            readTime: "7 min read",
            category: "Product",
            author: "Dan Jimmerson",
            image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=2070",
            content: `<p class="lead">Retention is the new acquisition. Understanding the psychological triggers that form habits is essential for product growth...</p>`
        },
        "building-for-the-spatial-web": {
            title: "Building for the Spatial Web",
            subtitle: "Preparing your design system for an immersive, 3D-first internet.",
            date: "Nov 15, 2025",
            readTime: "5 min read",
            category: "Technology",
            author: "Dan Jimmerson",
            image: "https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?auto=format&fit=crop&q=80&w=2070",
            content: `<p class="lead">The screen is dissolving. As we move towards spatial computing, our design systems must evolve from 2D planes to 3D environments...</p>`
        }
    };

    // Default to first post if slug not found (or handle 404)
    const post = POSTS[slug || "the-future-of-brand-architecture"] || POSTS["the-future-of-brand-architecture"];

    // Inject the long content if it's missing (for the new stubs)
    if (!post.content || post.content.length < 200) {
        post.content = `
    <p class="lead">This is a placeholder for the full article content. In a real application, this would be fetched from a CMS or markdown file.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <h2>The Core Concept</h2>
    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <blockquote>"Innovation distinguishes between a leader and a follower."</blockquote>
    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
    `;
    }

    return (
        <div className="min-h-screen bg-white text-gray-900 selection:bg-black selection:text-white">
            <Navigation alwaysShowBackground />

            <article className="pt-32 pb-20">
                {/* Header */}
                <div className="container mx-auto px-6 lg:px-12 max-w-4xl">
                    <div className="flex items-center justify-between mb-8">
                        <Link
                            to="/feed"
                            className="inline-flex items-center gap-2 text-gray-500 hover:text-black transition-colors group"
                        >
                            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" /> Back to Feed
                        </Link>

                        <div className="flex items-center gap-4">
                            <span className="px-3 py-1 bg-black text-white text-xs font-bold uppercase tracking-widest rounded-full">
                                {post.category}
                            </span>
                            <span className="flex items-center gap-1 text-sm text-gray-500 font-medium">
                                <Calendar className="w-4 h-4" /> {post.date}
                            </span>
                        </div>
                    </div>

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                    >

                        <h1 className="text-4xl lg:text-6xl font-serif font-bold leading-[1.1] mb-6 text-gray-900 tracking-tight">
                            {post.title}
                        </h1>

                        <p className="text-xl lg:text-2xl text-gray-600 leading-relaxed mb-8 font-light">
                            {post.subtitle}
                        </p>

                        <div className="flex items-center justify-between border-t border-b border-gray-100 py-6 mb-12">
                            <div className="flex items-center gap-3">
                                <div className="w-10 h-10 rounded-full bg-gray-200 overflow-hidden">
                                    <img src="https://github.com/shadcn.png" alt={post.author} className="w-full h-full object-cover" />
                                </div>
                                <div>
                                    <div className="font-bold text-sm">{post.author}</div>
                                    <div className="text-xs text-gray-500">{post.readTime}</div>
                                </div>
                            </div>
                            <div className="flex gap-4">
                                <button className="text-gray-400 hover:text-black transition-colors"><Twitter className="w-5 h-5" /></button>
                                <button className="text-gray-400 hover:text-black transition-colors"><Linkedin className="w-5 h-5" /></button>
                                <button className="text-gray-400 hover:text-black transition-colors"><Facebook className="w-5 h-5" /></button>
                                <button className="text-gray-400 hover:text-black transition-colors"><Share2 className="w-5 h-5" /></button>
                            </div>
                        </div>
                    </motion.div>
                </div>

                {/* Featured Image */}
                <motion.div
                    initial={{ opacity: 0, scale: 0.98 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: 0.2, duration: 0.8 }}
                    className="container mx-auto px-4 lg:px-8 mb-16 max-w-6xl"
                >
                    <div className="relative aspect-[21/9] overflow-hidden rounded-2xl shadow-sm">
                        <img
                            src={post.image}
                            alt={post.title}
                            className="w-full h-full object-cover"
                        />
                    </div>
                    <div className="text-center mt-4 text-sm text-gray-400 italic">
                        Photography by Unsplash
                    </div>
                </motion.div>

                {/* Content */}
                <div className="container mx-auto px-6 lg:px-12 max-w-3xl">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.4, duration: 0.6 }}
                        className="prose prose-lg md:prose-xl prose-slate max-w-none
              prose-headings:font-serif prose-headings:font-bold prose-headings:text-black prose-headings:tracking-tight prose-headings:mb-8 prose-headings:mt-16
              prose-h2:text-4xl md:prose-h2:text-5xl prose-h2:leading-tight
              prose-h3:text-3xl md:prose-h3:text-4xl prose-h3:leading-tight
              prose-h4:text-2xl md:prose-h4:text-3xl prose-h4:leading-tight
              prose-h5:text-xl md:prose-h5:text-2xl prose-h5:leading-tight
              prose-h6:text-lg md:prose-h6:text-xl prose-h6:leading-tight prose-h6:uppercase prose-h6:tracking-widest
              prose-p:font-sans prose-p:text-[1.125rem] md:prose-p:text-[1.25rem] prose-p:leading-[1.9] prose-p:text-gray-900 prose-p:font-normal prose-p:tracking-normal prose-p:mb-8
              prose-a:text-black prose-a:font-medium prose-a:no-underline hover:prose-a:underline
              prose-blockquote:border-l-4 prose-blockquote:border-black prose-blockquote:pl-8 prose-blockquote:py-4 prose-blockquote:my-12 prose-blockquote:italic prose-blockquote:text-2xl md:prose-blockquote:text-4xl prose-blockquote:font-serif prose-blockquote:text-black prose-blockquote:leading-tight
              prose-img:rounded-2xl prose-img:shadow-xl prose-img:my-16
              prose-li:text-lg prose-li:text-gray-900 prose-li:leading-relaxed
              [&>.lead]:text-2xl md:[&>.lead]:text-3xl [&>.lead]:font-serif [&>.lead]:text-black [&>.lead]:leading-[1.4] [&>.lead]:mb-16 [&>.lead]:font-medium"
                        dangerouslySetInnerHTML={{ __html: post.content }}
                    />

                    <div className="mt-20 pt-10 border-t border-gray-100">
                        <h3 className="font-serif font-bold text-2xl mb-6">More from the Feed</h3>
                        {/* Placeholder for related posts - could reuse Feed cards here */}
                        <div className="grid md:grid-cols-2 gap-8">
                            <div className="group cursor-pointer">
                                <div className="aspect-video bg-gray-100 rounded-xl mb-4 overflow-hidden">
                                    <img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2070" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                                </div>
                                <h4 className="font-serif font-bold text-xl mb-2 group-hover:underline">Revenue Systems that Scale</h4>
                                <p className="text-gray-500 text-sm">Business • 4 min read</p>
                            </div>
                            <div className="group cursor-pointer">
                                <div className="aspect-video bg-gray-100 rounded-xl mb-4 overflow-hidden">
                                    <img src="https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&q=80&w=2700" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                                </div>
                                <h4 className="font-serif font-bold text-xl mb-2 group-hover:underline">Design as a Competitive Advantage</h4>
                                <p className="text-gray-500 text-sm">Design • 6 min read</p>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    );
};

export default BlogPost;
