-- Create testimonials table
create table public.testimonials (
  id bigint generated by default as identity primary key,
  quote text not null,
  author text not null,
  role text not null,
  company text not null,
  image text not null,
  color text not null default '#6366f1',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.testimonials enable row level security;

-- Create policies
create policy "Allow public read access"
  on public.testimonials for select
  using (true);

create policy "Allow auth insert for admin"
  on public.testimonials for insert
  with check (auth.email() = 'jimmerson@gmail.com');

create policy "Allow auth update for admin"
  on public.testimonials for update
  using (auth.email() = 'jimmerson@gmail.com');

create policy "Allow auth delete for admin"
  on public.testimonials for delete
  using (auth.email() = 'jimmerson@gmail.com');
