-- 1. Ensure POSTS table exists (Safe to run if already exists)
CREATE TABLE IF NOT EXISTS public.posts (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    subtitle TEXT,
    slug TEXT UNIQUE NOT NULL,
    category TEXT,
    image TEXT,
    excerpt TEXT,
    date TEXT,
    "readTime" TEXT,
    author TEXT,
    content TEXT,
    type TEXT DEFAULT 'created',
    link TEXT,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('published', 'draft', 'trash'))
);

-- 2. Ensure TESTIMONIALS table exists
CREATE TABLE IF NOT EXISTS public.testimonials (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    quote TEXT NOT NULL,
    author TEXT NOT NULL,
    role TEXT,
    company TEXT,
    image TEXT,
    color TEXT,
    sort_order DOUBLE PRECISION DEFAULT 0
);

-- 3. Seed POSTS (Full Data)
INSERT INTO public.posts (title, subtitle, slug, category, image, excerpt, date, "readTime", author, content, type, link, status)
VALUES
(
    'Brand is the Only Moat Left in the Era of Infinite Slop',
    'When the cost of creating ''average'' drops to zero, the value of ''trust'' becomes infinite.',
    'brand-is-the-only-moat',
    'Strategy',
    'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=2070',
    'Why Brand Search Volume is the only metric that matters in 2026.',
    'Dec 12, 2025',
    '7 min read',
    'Dan Jimmerson',
    '<p class="lead">We are drowning.</p><p>Open your LinkedIn feed. Search for a recipe. Look for coding advice. You are wading through a torrent of what the internet intelligentsia has aptly named "AI Slop." It is grammatically correct, structurally sound, and completely soulless content generated at a scale the human mind can barely comprehend.</p><p>Generative AI has reduced the marginal cost of content creation to effectively zero. When supply becomes infinite, basic economics dictates that price (value) crashes to zero. If you are competing on "content," "information," or "utility," you are competing against a tsunami with a bucket. You will lose.</p><p>In this new reality, the only asset that cannot be synthesized, prompted, or scraped is <strong>Brand</strong>.</p><h2>The Data: The Great Commoditization</h2><p>Let’s look at the numbers. According to Gartner’s latest projections, by the end of 2026, search engine volume will drop by <strong>25%</strong> as users shift to AI agents (ChatGPT, Claude, Gemini) for answers. But the more terrifying stat comes from a recent Europol report, estimating that up to <strong>90% of online content could be synthetically generated by 2026</strong>.</p><h2>The "Entity" Shift: Why Google Craves Brands</h2><p>In the old world of SEO, you ranked for "best running shoes" by writing a 2,000-word guide about running shoes. In the AI era, an LLM (Large Language Model) can write that guide in 4 seconds.</p><p>So, how does a search engine decide what is real? It looks for the Entity. It looks for the Brand.</p><p>Data from Moz and Semrush volatility trackers shows a clear trend: sites with high "Brand Authority" are surviving core updates, while niche affiliate sites—even those with great content—are being obliterated. Google is essentially asking: <em>Does this website represent a real business with real customers, or is it just a content farm?</em></p><h2>Brand Search Volume: The New North Star</h2><p>Forget "Keyword Volume." The most critical metric in your dashboard right now is <strong>Brand Search Volume</strong>.</p><p>How many people are typing "Nike" instead of "running shoes"? How many people are typing "Morgan and Morgan" instead of "car accident lawyer"?</p><p>When a user searches for your brand explicitly, they are bypassing the AI filter. They are bypassing the Google AI Overview (which steals your clicks). They are navigating directly to you.</p><h2>The "Un-Googleable" Experience</h2><p>Scott Galloway, the NYU marketing professor, has been banging this drum for years, but the AI era has proven him prophetic. He argues that the strongest brands are the ones that offer an irrational premium or an experience that cannot be digitized.</p><p>To survive the "Slop Era," you must double down on what AI cannot do:</p><ul><li><strong>Opinion & Contrarianism:</strong> AI is designed to be average and safe. Human brands can take a stand.</li><li><strong>Community & Connection:</strong> AI can simulate a chat, but it cannot simulate a congregation.</li><li><strong>High-Stakes Accountability:</strong> If ChatGPT gives you bad legal advice, you can''t sue it. If a branded law firm does, you can. That accountability is the value proposition.</li></ul><h2>The Verdict: Be Famous or Be Forgotten</h2><p>In the age of AI, "average" is a death sentence. Being a "good enough" provider of a commodity service is no longer a business model. It is a waiting room for bankruptcy.</p><p>The winners of the next decade will not be the ones with the best SEO strategy. They will be the ones who built a reputation so strong that customers tell their AI agents: <em>"Don''t just find me a coffee shop. Find me a Starbucks."</em></p><h3>Your Action Plan:</h3><ol><li>Stop writing "SEO content." Start writing "Thought Leadership." If an AI could have written your blog post, delete it.</li><li>Measure "Direct Traffic" and "Brand Search." These are your true health metrics.</li><li>Invest in "Real World" marketing. Billboards, events, podcasts, physical mailers. These generate the brand signals that digital algorithms eventually pick up on.</li></ol><p>Brand is the only thing the algorithm can''t steal. Protect it with your life.</p>',
    'created',
    NULL,
    'published'
),
(
    'Local SEO is Dead. Long Live ''Local Engagement.''',
    'The 2026 Whitespark Report confirms what we feared: If you aren''t ''living'' inside your Google Business Profile, you are invisible.',
    'local-seo-is-dead',
    'Marketing',
    'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=2074',
    'The 2026 Whitespark Report confirms what we feared: If you aren''t ''living'' inside your Google Business Profile, you are invisible.',
    'Dec 10, 2025',
    '6 min read',
    'Dan Jimmerson',
    '<p class="lead">For years, the Local SEO playbook was comfortable. It was a checklist. Optimize the title tag, stuff some keywords into the business description, build a few citations on sites nobody visits, and wait for the phone to ring.</p><p>The release of Whitespark’s 2026 Local Search Ranking Factors report—the industry’s bible, curated by Darren Shaw and fueled by the insights of the world’s top local search experts—has drawn a line in the sand. The era of "Set and Forget" is over. We have entered the era of <strong>Local Engagement</strong>.</p><h2>The Headline Data: Participation is the New Optimization</h2><p>The experts ranked "Quantity of Engagement Signals" (clicks, calls, direction requests) and "Behavioral Signals" higher than ever before. But here is the kicker: Google isn''t just measuring how customers interact with you. They are measuring how you interact with the platform.</p><p><strong>"Response Times"</strong> has cracked the top 4 ranking factors. Let that sink in. How fast you reply to a message or a review is now weighted as heavily as your primary category. Google is effectively saying: <em>If you aren''t home, we aren''t sending guests to your door.</em></p><h2>The "Open Now" Algorithm Shift</h2><p>Perhaps the most controversial and data-backed finding in the new report is the massive weight given to "Business is Open at Time of Search." It ranked as the <strong>#5 overall factor</strong> for ranking in the Local Pack.</p><p>This is a brutal reality check for the 9-to-5 business. If a user searches for "personal injury lawyer" at 6:00 PM and you close at 5:00 PM, Google is actively suppressing your listing in favor of the firm that stays open until 7:00 PM.</p><h2>The "Predefined Services" Gold Rush</h2><p>If you want a quick win, look at the data around GBP Services. The factor "Keywords in GBP Services" saw a massive 75-point increase in importance score compared to previous years. This is the single biggest "easy win" available right now.</p><h2>The Fall of the "Old Guard" Tactics</h2><p>To make room for engagement signals, the algorithm had to dump the dead weight. The 2026 report highlights the losers: <strong>Internal Links</strong>, <strong>Citations</strong>, and <strong>Linking Out</strong> are all down.</p><h2>Social Signals: The Debate is Finally Over</h2><p>For a decade, SEOs argued about whether social media impacted SEO. Whitespark’s 2026 report has ended the argument. <strong>Social Signals have officially entered the chat</strong> as a measurable ranking factor.</p><h2>The Verdict: Brand Trust is the Algorithm</h2><p>Whitespark’s data points to a singular conclusion: Google is trying to emulate word-of-mouth at scale. The top factors—Reviews, Response Time, Engagement, Opening Hours—are all proxies for trust. In an age where AI can spin up a fake website in seconds, Google is retreating to the one thing AI can''t easily fake: real-world activity.</p><h3>Your Action Plan:</h3><ol><li>Audit your "Predefined Services" immediately. Tick every box that applies.</li><li>Fix your hours. If you have an answering service, you are open. Mark it.</li><li>Treat GBP like Instagram. Post photos and updates weekly. Not for the clicks, but for the pulse check.</li><li>Reply instantly. Response time is a ranking factor. Treat it like a 911 call.</li></ol><p>The days of "SEO tricks" are gone. The data says: Be a better business, and you will rank. Be a dormant business, and you will disappear.</p>',
    'created',
    NULL,
    'published'
),
(
    'CRO is Dead. Welcome to the Age of ''User Intuition.''',
    'Stop testing button colors. Stop obsessing over font sizes. The 2026 consumer is too exhausted to care.',
    'cro-is-dead',
    'Optimization',
    'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=2070',
    'If you want them to convert, you have to stop making them think.',
    'Dec 8, 2025',
    '5 min read',
    'Dan Jimmerson',
    '<p class="lead">For the last decade, Conversion Rate Optimization (CRO) has been the playground of the insecure marketer. It was a safe haven of A/B tests that didn''t matter.</p><p>This is "deck chair optimization"—rearranging the furniture on the Titanic while the ship sinks. In 2026, the ship is sinking because the user’s brain is drowning.</p><p>The era of "tactical CRO" is dead. We have entered the era of <strong>Cognitive Load Minimization</strong>. The winners of the next five years won’t be the ones with the best landing page builders. They will be the ones who understand the neuroscience of a distracted, skeptical, and exhausted population.</p><h2>The "Local Maximum" Trap</h2><p>The vast majority of CRO programs today are stuck at what mathematicians call a "local maximum." You have optimized a mediocre page to be the best possible version of a mediocre page.</p><p>According to data from VWO and Optimizely, nearly 80% of A/B tests fail to produce a statistically significant result. Why? Because you are testing variables that the user doesn''t care about.</p><h2>The New KPI: "Time to Value" (TTV)</h2><p>In 2025-2026, the only metric that correlates perfectly with conversion is Speed. Not just page load speed (though Google’s Core Web Vitals data confirms that a 1-second delay still drops conversions by up to 20%), but <strong>Cognitive Speed</strong>.</p><h2>The Death of the "Sales Funnel" & The Rise of "Micro-Moments"</h2><p>The traditional "Funnel" (Awareness -> Interest -> Desire -> Action) assumes the user is rational and linear. They aren''t.</p><p>Google’s research on "Micro-Moments" has evolved into a chaotic web of touchpoints. A user might see a TikTok (Discovery), search Reddit for "is [Brand] legit?" (Validation), and then click an Instagram retargeting ad to buy (Conversion).</p><h3>The Strategy: You need Dynamic Personalization.</h3><ul><li><strong>Segment by Source:</strong> Traffic from a "Comparison Review" blog post should land on a page that highlights specs and pricing.</li><li><strong>Segment by Intent:</strong> Traffic from a "Brand Name" search should land on a page that highlights trust and offers.</li></ul><h2>Trust Signals: The 108% Lift</h2><p>Here is the most punchy stat you will read today: <strong>Customers who engage with reviews are 108.3% more likely to convert.</strong></p><p>But here is the catch: They don''t trust <em>your</em> reviews. They trust third-party verification.</p><h2>The Verdict: Optimize for "Don''t Make Me Think"</h2><p>Steve Krug wrote <em>Don''t Make Me Think</em> in 2000. It is more relevant in 2026 than the day it was published.</p><h3>Your Action Plan:</h3><ol><li>Audit your "Cognitive Load." Print your landing page. Hand it to a stranger. Give them 5 seconds. Take it away. Ask them: "What does this company sell?" If they can''t answer, start over.</li><li>Implement "Zero-Party Data" Collection. Instead of a pop-up asking for an email, use a Quiz. "What is your biggest struggle right now?" -> [Answer] -> "Here is the solution." This converts 2-3x higher than generic forms.</li><li>Speed is a Feature. If your mobile site takes 3 seconds to load, no amount of copywriting will save you. Fix the tech stack first.</li></ol><p>CRO isn''t about tricking people into clicking. It''s about removing the obstacles that stop them from doing what they already want to do.</p>',
    'created',
    NULL,
    'published'
),
(
    'The Collapse of Traditional Search. Why You Must Be ''Everywhere.''',
    'Google is no longer the homepage of the internet. It is just another app. If your strategy relies solely on ''ranking #1,'' you are invisible to half the population.',
    'collapse-of-traditional-search',
    'Strategy',
    'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=2070',
    'We are witnessing the ''fragmentation of intent.'' Users are no longer going to one place for everything.',
    'Dec 5, 2025',
    '6 min read',
    'Dan Jimmerson',
    '<p class="lead">For twenty years, the internet had a front door. Its name was Google.</p><p>If you wanted to buy a product, you Googled it. If you wanted to find a restaurant, you Googled it. If you needed an answer, you Googled it. The strategy was simple: Optimize for the door, and you capture the traffic.</p><p>That door has been smashed wide open.</p><h2>The Data: The Generational Exodus</h2><p>The numbers are not just bad for Google. They are catastrophic for traditional SEOs.</p><p>According to EMARKETER, nearly <strong>46% of Gen Z now prefer social media (TikTok and Instagram) over Google for search</strong>. They are not using TikTok to watch dances. They are using it to find lunch spots, financial advice, and skincare routines.</p><h2>The "Zero-Click" Crisis</h2><p>Even if you do rank #1 on Google, it might not matter.</p><p>SparkToro and Jumpshot have been tracking the "Zero-Click" phenomenon for years. The latest data is alarming. In late 2025, it is estimated that nearly <strong>58% of Google searches end without a click</strong>.</p><h2>Amazon: The New Product Search Engine</h2><p>If you sell products, your SEO competitor isn''t another website. It is Amazon.</p><p>Data from Jungle Scout reveals that <strong>56% of consumers start their product search directly on Amazon</strong>. They skip Google entirely. They want reviews, shipping speed, and price comparisons instantly.</p><h2>The Rise of "Search Everywhere" Optimization</h2><p>So, what is the solution? You must stop doing "SEO" and start doing "Search Everywhere Optimization."</p><p>You need to be the answer on the platform where the question is actually being asked.</p><ul><li><strong>The "How-To" Search:</strong> Happens on YouTube and TikTok.</li><li><strong>The "Validation" Search:</strong> Happens on Reddit. (Google "Reddit" search volume has exploded because users trust real humans over SEO blogs).</li><li><strong>The "Transaction" Search:</strong> Happens on Amazon.</li><li><strong>The "Explanation" Search:</strong> Happens on ChatGPT and Perplexity.</li></ul><h2>The Verdict: Be Native or Be Nothing</h2><p>You cannot just copy-paste your blog post to these platforms. The collapse of traditional search is not the end of digital marketing. It is the end of lazy digital marketing. The audience is still there. They just aren''t all standing at the same front door anymore. You have to go find them.</p>',
    'created',
    NULL,
    'published'
),
(
    'The Future of Brand Architecture',
    'How modern companies are rethinking their structural identity in a decentralized world.',
    'the-future-of-brand-architecture',
    'Strategy',
    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=2070',
    'How modern companies are rethinking their structural identity in a decentralized world. The old playbooks for brand building are being rewritten by DAOs, community-led growth, and AI-driven personalization.',
    'Nov 28, 2025',
    '5 min read',
    'Dan Jimmerson',
    '<p class="lead">In the rapidly evolving landscape of digital business, the traditional models of brand architecture are not just being challenged—they are being dismantled. The old playbooks for brand building, predicated on centralized control and unidirectional messaging, are being rewritten by the decentralized logic of Web3, the collective power of DAOs, and the hyper-personalization capabilities of AI.</p><p>We are witnessing a paradigm shift from <strong>Monolithic Branding</strong>—where a single entity dictates identity, voice, and value—to <strong>Mesh Branding</strong>, where value is co-created, distributed, and governed by communities. This isn''t a subtle pivot; it''s a structural revolution. As we move through 2025, the brands that will thrive are those that understand how to architect themselves not as castles to be defended, but as ecosystems to be cultivated.</p><h2>1. The Decentralized Shift: Why Control is Dying</h2><p>The concept of "brand management" has historically implied control. Brand managers curated the logo, the voice, the message, and the channel. But the rise of Web3 technologies has fundamentally altered the power dynamics of the internet. We are moving from the "Read-Write" era of Web2 to the "Read-Write-Own" era of Web3. In this new world, consumers expect more than just consumption; they demand ownership.</p><h2>2. DAO Dynamics: 13,000 Organizations Can''t Be Wrong</h2><p>Perhaps the most potent manifestation of this new architecture is the Decentralized Autonomous Organization (DAO). DAOs represent a radical rethinking of corporate structure, replacing the top-down C-suite with smart contracts and community governance. While it sounds futuristic, the impact is already measurable and massive.</p><h2>3. The New Loyalty Loop: Ownership as Marketing</h2><p>If DAOs are the boardroom, then NFTs (Non-Fungible Tokens) and social tokens are the membership cards. The 2021 boom might have been fueled by speculation, but the 2025 reality is driven by utility. Smart brands are using NFTs to reinvent loyalty.</p><h2>4. AI & The Personalized Brand</h2><p>While decentralization distributes control, Artificial Intelligence is scaling personalization to god-like levels. The two trends are not contradictory; they are complementary. AI is the engine that will allow decentralized brands to treat every single one of their millions of community members as individuals.</p><h2>5. The Metaverse Horizon: The Spatial Web</h2><p>Finally, brand architecture must literally "architect" 3D spaces. The Spatial Web (or Metaverse) is not a video game; it''s the next iteration of the mobile internet. It dissolves the screen.</p><h2>6. Implications for the Modern Architect</h2><p>So, what does the future of brand architecture look like? It looks like a network, not a hierarchy.</p><ol><li><strong>Fluid Identity:</strong> Logos and visual systems must be dynamic, adapting to 2D screens, 3D worlds, and even AR overlays.</li><li><strong>Community Governance:</strong> The CMO of 2030 might report to a DAO, not a CEO. Decisions on product roadmaps will be voted on on-chain.</li><li><strong>Interoperability:</strong> A brand''s digital assets (virtual clothing, tools, credentials) must work across different platforms. The era of the "walled garden" is under siege.</li></ol><p>The future isn''t just about building a better brand. It''s about building a brand that others can build <em>upon</em>. The brands that win will be the ones that provide the strongest foundation for their communities to construct their own meaning, value, and identity.</p>',
    'created',
    NULL,
    'published'
),
(
    'Design as a Competitive Advantage',
    'Why aesthetic excellence is no longer optional for market leaders in the AI era.',
    'design-as-a-competitive-advantage',
    'Design',
    'https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&q=80&w=2700',
    'Why aesthetic excellence is no longer optional for market leaders in the AI era.',
    'Nov 22, 2025',
    '6 min read',
    'Dan Jimmerson',
    '<p class="lead">In an age of infinite content generated by AI, distinct human-centric design is no longer just a "nice-to-have" aesthetic layer; it is the ultimate economic moat. While technology has democratized functionality—anyone can build an app—it has not democratized taste. As we move into the AB test-saturated landscape of 2025, design has ceased to be about decoration and has started to be about domination.</p><p>The market has spoken, and its message is brutal: if your product functions but fails to feel inevitable, you are already dead. The companies winning today aren''t just engineering-led; they are design-led. This is the era where aesthetic excellence correlates directly with stock performance, and where a 50-millisecond delay in visual processing can cost millions in revenue.</p><h2>1. The 228% Premium: Design as Alpha</h2><p>For decades, design was viewed by the C-suite as a cost center—something to be "sprinkled on" after the engineers finished the real work. The data now proves this worldview is not just outdated; it is negligent.</p><p>The Design Management Institute''s (DMI) Index reveals a staggering truth: <strong>Design-led companies have outperformed the S&P 500 significantly over a 10-year period</strong>. Adobe''s analysis corroborates this, showing a <strong>228% outperformance</strong>.</p><h2>2. The ROI of UX: The 9,900% Multiplier</h2><p>If the macro stock data is compelling, the micro unit economics are overwhelming. The Return on Investment (ROI) for User Experience (UX) design is widely cited at <strong>9,900%</strong>. That is, for every <strong>$1 invested in UX, the return is $100</strong>.</p><h2>3. The 50-Millisecond Verdict</h2><p>We often talk about "brand loyalty," but the reality is "brand snap-judgment." Humans are visual creatures, evolved to assess threats and opportunities in microseconds. This biological imperative translates directly to digital design.</p><p>Research confirms that it takes just <strong>0.05 seconds (50 milliseconds)</strong> for a user to form an opinion about your website. Crucially, <strong>94% of that first impression is design-related</strong>. It''s not your copy; it''s not your pricing; it''s your layout, typography, and visual hierarchy.</p><h2>4. Trust, Loyalty, and the "Design Moat"</h2><p>In a low-trust digital environment (deepfakes, scams, infinite spam), high-fidelity design is a proxy for legitimacy. It signals, "We care about details because we have the resources and competence to do so."</p><h2>5. The Future: Design in the Age of AI</h2><p>As AI tools like Midjourney and Galileo commoditize asset generation, the role of the designer shifts from "maker" to "conductor." The competitive advantage will not be in <em>generating</em> the UI, but in <em>curating</em> the experience.</p><h2>Conclusion</h2><p>Design is no longer a wrapper; it is the product. It is the business model. It is the stock price. To ignore design in 2025 is to choose voluntary obsolescence. The companies that win will be those that treat every pixel as a capital allocation decision.</p>',
    'created',
    NULL,
    'published'
)
ON CONFLICT (slug) DO UPDATE SET 
content = EXCLUDED.content,
status = EXCLUDED.status;

-- 4. Seed TESTIMONIALS (Full Data)
INSERT INTO public.testimonials (id, quote, author, role, company, image, color, sort_order)
VALUES
(
    1,
    'Dan is one of the most talented digital marketing, technology and branding strategist that I’ve ever worked with. I worked and learned a lot from Dan during our time at an e-Commerce Marketing Automation startup. His go-to-market & branding strategy was brilliant and quickly helped drive revenue and new customers. It was at this moment that I realized that Dan was a natural talent and a true professional in his craft. If your looking for a world-class, innovative, results focused Marketer & Branding expert to help grow your business and drive real business results. I would highly suggest you give Dan a call right now. Highly recommended.',
    'Sal Stabler',
    'Co-Founder and CEO',
    'Nexlayer',
    '/assets/testimonials/testimonial-sal-new.jpg',
    '#6366f1',
    0
),
(
    2,
    'Dan is one of the most knowledgeable and dedicated persons that I have had the pleasure of working with in my career. Dan vigorously keeps up to date in current trends from marketing to technology. He is a very insightful people person and has the moral foundation that will add value to any organization. Dan is a visionary with a old soul which enables him to relate to multiple persons and also look to the future with respect for the past. Dan clearly defines his goals and approach to projects and completes task in a timely manner. Dan is able to lead multiple staff and teams within an organization and is an executive level professional.',
    'John Malcolm',
    'Chief Innovation and Technology Officer',
    'Cleveland Public Library',
    '/assets/testimonials/testimonial-john-new.jpg',
    '#10b981',
    1
),
(
    3,
    'Dan is a thought leader and innovator in the field of marketing. I''ve had the pleasure of working with Dan for the past 6 years and the results he''s produced for us have been tremendous. He has the ability to think long term but not lose sight of what''s needed each day to achieve our goals. Dan stays on top of the most current and effective techniques to generate new leads to keep our company a few steps ahead of our competition. By far, the smartest, most creative, and most capable head of marketing that I''ve worked with in my 25 year career.',
    'Keith Vargo',
    'President',
    'Vargo Consultants, LLC',
    '/assets/testimonials/testimonial-keith-new.jpg',
    '#f59e0b',
    2
),
(
    4,
    'Dan is one of the most talented, creative and results oriented marketing professionals that I have ever had the pleasure to work with. Dan has a great ability to process new concepts and turn them into solid action plans that drive business. I would always welcome the opportunity to work with Dan.',
    'Leigh Orlov',
    'Co-Founder',
    'CoCENTRIX',
    '/assets/testimonials/testimonial-leigh.jpg',
    '#ec4899',
    3
),
(
    5,
    'Dan Jimmerson brings passion, deep knowledge of his customer base and an incredible amount of marketing know-how to work each day. I had the pleasure of working with Dan when he was in the Microsoft partner channel and he was exceptional. He not only developed a strong pipeline but also customer relationships, which were instrumental in driving continued success.',
    'Allison Dawson',
    'VP of Field Marketing, North America',
    'Zendesk',
    '/assets/testimonials/testimonial-allison-new.jpg',
    '#8b5cf6',
    4
),
(
    6,
    'I worked with Dan Jimmerson while he was the Senior Marketing Director at CoCentrix. Dan is absolutely one of the most talented marketing professionals I have known in my entire career. He is not only passionate and great to work with, but has such a deep understanding of how marketing can directly impact and influence the bottom line. Dan would be an exceptional asset to any organization he was affiliated with.',
    'Wendy Nossaman',
    'Director, AI Workforce Solutions',
    'Microsoft',
    '/assets/testimonials/testimonial-wendy-new.jpg',
    '#3b82f6',
    5
)
ON CONFLICT (id) DO UPDATE SET 
sort_order = EXCLUDED.sort_order,
color = EXCLUDED.color,
image = EXCLUDED.image;
