
export interface BlogPost {
    id: string | number;
    title: string;
    subtitle?: string;
    slug: string;
    category: string;
    image: string;
    excerpt?: string;
    date: string;
    readTime: string;
    author?: string;
    content?: string;
    type?: 'created' | 'curated';
    link?: string;
}

export const BLOG_POSTS: Record<string, BlogPost> = {
    "the-future-of-brand-architecture": {
        id: 1,
        title: "The Future of Brand Architecture",
        subtitle: "How modern companies are rethinking their structural identity in a decentralized world.",
        slug: "the-future-of-brand-architecture",
        category: "Strategy",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=2070",
        excerpt: "How modern companies are rethinking their structural identity in a decentralized world. The old playbooks for brand building are being rewritten by DAOs, community-led growth, and AI-driven personalization.",
        date: "Nov 28, 2025",
        readTime: "5 min read",
        author: "Dan Jimmerson",
        type: "created",
        content: `<p class="lead">In the rapidly evolving landscape of digital business, the traditional models of brand architecture are being challenged...</p>`
    },
    "revenue-systems-that-scale": {
        id: 2,
        title: "Revenue Systems that Scale",
        subtitle: "Building automated pipelines that turn passive attention into active revenue streams.",
        slug: "revenue-systems-that-scale",
        category: "Business",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2070",
        excerpt: "Building automated pipelines that turn passive attention into active revenue streams.",
        date: "Nov 25, 2025",
        readTime: "4 min read",
        author: "Dan Jimmerson",
        type: "created",
        content: `<p class="lead">Revenue is no longer just about sales; it's about systems. In the modern economy, the most successful companies are those that build automated engines...</p>`
    },
    "design-as-a-competitive-advantage": {
        id: 3,
        title: "Design as a Competitive Advantage",
        subtitle: "Why aesthetic excellence is no longer optional for market leaders in the AI era.",
        slug: "design-as-a-competitive-advantage",
        category: "Design",
        image: "https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&q=80&w=2700",
        excerpt: "Why aesthetic excellence is no longer optional for market leaders in the AI era.",
        date: "Nov 22, 2025",
        readTime: "6 min read",
        author: "Dan Jimmerson",
        type: "created",
        content: `<p class="lead">In an age of infinite content generated by AI, human curation and high-fidelity design become the ultimate differentiators...</p>`
    },
    "the-psychology-of-user-retention": {
        id: 4,
        title: "The Psychology of User Retention",
        subtitle: "Understanding the cognitive biases that keep users coming back to your application.",
        slug: "the-psychology-of-user-retention",
        category: "Product",
        image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=2070",
        excerpt: "Understanding the cognitive biases that keep users coming back to your application.",
        date: "Nov 18, 2025",
        readTime: "7 min read",
        author: "Dan Jimmerson",
        type: "created",
        content: `<p class="lead">Retention is the new acquisition. Understanding the psychological triggers that form habits is essential for product growth...</p>`
    },
    "the-psychology-of-micro-interactions": {
        id: 401,
        title: "The Psychology of Micro-interactions",
        subtitle: "How small animations create big emotional connections.",
        slug: "the-psychology-of-micro-interactions",
        category: "UX/UI",
        image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=2564",
        excerpt: "Details are not just details; they make the design. Micro-interactions are the secret sauce of delightful user experiences.",
        date: "Sep 15, 2024",
        readTime: "5 min read",
        author: "Dan Jimmerson",
        type: "created",
        content: `<p class="lead">In the world of UI design, the difference between good and great often lies in the micro-interactions...</p>`
    },
    "building-for-the-spatial-web": {
        id: 5,
        title: "Building for the Spatial Web",
        subtitle: "Preparing your design system for an immersive, 3D-first internet.",
        slug: "building-for-the-spatial-web",
        category: "Technology",
        image: "https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?auto=format&fit=crop&q=80&w=2070",
        excerpt: "Preparing your design system for an immersive, 3D-first internet.",
        date: "Nov 15, 2025",
        readTime: "5 min read",
        author: "Dan Jimmerson",
        type: "created",
        content: `<p class="lead">The screen is dissolving. As we move towards spatial computing, our design systems must evolve from 2D planes to 3D environments...</p>`
    },
    "the-end-of-average": {
        id: 101,
        title: "The End of Average",
        slug: "the-end-of-average",
        category: "Inspiration",
        image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&q=80&w=2068",
        excerpt: "A compelling look at why standard metrics fail to capture individual potential. Found this incredibly relevant to modern team building.",
        date: "Nov 27, 2025",
        readTime: "External",
        type: "curated",
        link: "https://example.com/end-of-average"
    },
    "minimalism-in-complex-systems": {
        id: 102,
        title: "Minimalism in Complex Systems",
        slug: "minimalism-in-complex-systems",
        category: "Architecture",
        image: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&q=80&w=2070",
        excerpt: "Great breakdown of how complex backends can still maintain minimal, maintainable frontends.",
        date: "Nov 20, 2025",
        readTime: "External",
        type: "curated",
        link: "https://example.com/minimalism"
    }
};

export const getAllPosts = () => Object.values(BLOG_POSTS);
export const getPostBySlug = (slug: string) => BLOG_POSTS[slug];
